### ISSUE TITLE
multiple device login

### ISSUE THREAD

**Issue by mimoudix** [brauck/Login-System#1]
The remember me doesn't support the login from multiple devices as the remember_me function tends to delete all related tokens, and so does the logout function.

**Comment by MrFOXINGER** [comment]
Hello, I would love to use this great login system! 
I use php 8.2 - the FILTER_SANITIZE_STRING used in libs/sannitization.php and in src/auth.php is deprecated since php 8.1
I am not able to change the FILTER_SANITIZE_STRING setting so that the script works.
I've already tried a few things, but I couldn't get the login system to work.
Could you please adjust this?
